# Generated by Django 5.2 on 2025-05-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_rename_is_activo_auth_is_active_auth_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
